language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - clang-3.5
    - libboost-all-dev
    - g++-5
sudo: required
install:
  - git clone https://github.com/miloyip/rapidjson rapidjson
  - sudo mv rapidjson/include/rapidjson /usr/include
before_script:
  - export CXX_GCC="g++-5"
  - export CXX_CLANG="clang++-3.5"
script:
  - scons -Q
  - scons -Q --lto