language: cpp
addons:
  apt:
    packages:
    - clang-3.3
sudo: required
install:
  - git clone https://github.com/miloyip/rapidjson rapidjson
  - mv rapidjson/include/rapidjson /usr/include
script:
  - scan-build scons -Q
  - scan-build scons -Q --lto