// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.



#ifndef STACKCPP_BADGE_H
#define STACKCPP_BADGE_H

#include "stackcpp/misc/flags.hpp"
#include "stackcpp/misc/types.hpp"
#include "stackcpp/objects/shallow_user.hpp"

#include <string>



namespace stackcpp {

inline namespace objects { struct badge; }
badge parse_badge(const rapidjson::Value&);



inline namespace objects {
struct badge final {
    integer_t amount() const noexcept { return amount_; }
    unique_id id() const noexcept { return id_; }
    badge_type type() const noexcept { return type_; }
    std::string description() const noexcept { return description_; }
    std::string url() const noexcept { return url_; }
    std::string name() const noexcept { return name_; }
    badge_rank rank() const noexcept { return rank_; }
    shallow_user user() const noexcept { return user_; }

private:
    friend badge stackcpp::parse_badge(const rapidjson::Value&);

    // See [dcl.fct.def.default]/4 and [dcl.init.aggr]/1 for rational.
    badge() noexcept {}

    integer_t amount_{};
    unique_id id_;
    badge_type type_{};
    std::string description_;
    std::string url_;
    std::string name_;
    badge_rank rank_{};
    shallow_user user_;
};
}
}

#endif
