// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.



#ifndef STACKCPP_CLOSED_DETAIL_HPP
#define STACKCPP_CLOSED_DETAIL_HPP

#include "stackcpp/objects/original_question.hpp"
#include "stackcpp/objects/shallow_user.hpp"

#include <rapidjson/document.h>
#include <string>
#include <vector>



namespace stackcpp {

inline namespace objects { struct closed_detail; }
closed_detail parse_closed_detail(const rapidjson::Value&);



inline namespace objects {
struct closed_detail final {
    std::vector<shallow_user> users() const noexcept { return users_; }
    std::string description() const noexcept { return description_; }
    bool on_hold() const noexcept { return on_hold_; }
    std::vector<original_question> original_questions() const noexcept { return original_questions_; }
    std::string reason() const noexcept { return reason_; }

private:
    friend closed_detail stackcpp::parse_closed_detail(const rapidjson::Value&);
    friend struct question;

    // See [dcl.fct.def.default]/4 and [dcl.init.aggr]/1 for rational.
    closed_detail() noexcept {}

    std::vector<shallow_user> users_;
    std::string description_;
    bool on_hold_{};
    std::vector<original_question> original_questions_;
    std::string reason_;
};
}
}

#endif
