// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.



#ifndef STACKCPP_COMMENT_HPP
#define STACKCPP_COMMENT_HPP

#include "stackcpp/misc/flags.hpp"
#include "stackcpp/misc/types.hpp"
#include "stackcpp/objects/shallow_user.hpp"

#include <rapidjson/document.h>
#include <string>
#include <vector>



namespace stackcpp {

inline namespace objects { struct comment; }
comment parse_comment(const rapidjson::Value&);



inline namespace objects {
// Represents a StackExchange comment.
struct comment final {
    std::string content() const noexcept { return content_; }
    std::string content_markdown() const noexcept { return content_markdown_; }
    bool flag() const noexcept { return flag_; }
    unique_id id() const noexcept { return id_; }
    date_t creation() const noexcept { return creation_; }
    bool edited() const noexcept { return edited_; }
    std::string url() const noexcept { return url_; }
    shallow_user owner() const noexcept { return owner_; }
    unique_id post_id() const noexcept { return post_id_; }
    stackcpp::post_type post_type() const noexcept { return post_type_; }
    shallow_user reply_to() const noexcept { return reply_to_; }
    integer_t score() const noexcept { return score_; }
    bool has_upvoted() const noexcept { return has_upvoted_; }

private:
    friend comment stackcpp::parse_comment(const rapidjson::Value&);

    // See [dcl.fct.def.default]/4 and [dcl.init.aggr]/1 for rational.
    comment() noexcept {}

    std::string content_;
    std::string content_markdown_;
    bool flag_{};
    unique_id id_;
    date_t creation_;
    bool edited_{};
    std::string url_;
    shallow_user owner_;
    unique_id post_id_;
    stackcpp::post_type post_type_{};
    shallow_user reply_to_;
    integer_t score_{};
    bool has_upvoted_{};
};
}
}

#endif
