// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.



#ifndef STACKCPP_MIGRATION_INFO_HPP
#define STACKCPP_MIGRATION_INFO_HPP

#include "stackcpp/misc/types.hpp"
#include "stackcpp/objects/site.hpp"



namespace stackcpp {

inline namespace objects { struct migration_info; }
migration_info parse_migration_info(const rapidjson::Value&);



inline namespace objects {
struct migration_info final {
    date_t date() const noexcept { return date_; }
    site other_site() const noexcept { return other_site_; }
    unique_id question_id() const noexcept { return question_id_; }

private:
    friend migration_info stackcpp::parse_migration_info(const rapidjson::Value&);
    friend struct question;

    // See [dcl.fct.def.default]/4 and [dcl.init.aggr]/1 for rational.
    migration_info() noexcept {}

    date_t date_;
    site other_site_;
    unique_id question_id_;
};
}
}

#endif
