// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.



#ifndef STACKCPP_NETWORK_ACTIVITY_HPP
#define STACKCPP_NETWORK_ACTIVITY_HPP

#include "stackcpp/misc/flags.hpp"
#include "stackcpp/misc/types.hpp"

#include <rapidjson/document.h>
#include <string>
#include <vector>



namespace stackcpp {

inline namespace objects { struct network_activity; }
network_activity parse_network_activity(const rapidjson::Value&);



inline namespace objects {
struct network_activity final {
    unique_id account_id() const noexcept { return account_id_; }
    activity_type activity() const noexcept { return activity_; }
    std::string api_site() const noexcept { return api_site_; }
    unique_id badge_id() const noexcept { return badge_id_; }
    date_t creation() const noexcept { return creation_; }
    std::string description() const noexcept { return description_; }
    std::string url() const noexcept { return url_; }
    unique_id post_id() const noexcept { return post_id_; }
    integer_t score() const noexcept { return score_; }
    std::vector<std::string> tags() const noexcept { return tags_; }
    std::string title() const noexcept { return title_; }

private:
    friend network_activity stackcpp::parse_network_activity(const rapidjson::Value&);

    // See [dcl.fct.def.default]/4 and [dcl.init.aggr]/1 for rational.
    network_activity() noexcept {}

    unique_id account_id_;
    activity_type activity_{};
    std::string api_site_;
    unique_id badge_id_;
    date_t creation_;
    std::string description_;
    std::string url_;
    unique_id post_id_;
    integer_t score_{};
    std::vector<std::string> tags_;
    std::string title_;
};
}
}

#endif
