// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.



#ifndef STACKCPP_NETWORK_USER_HPP
#define STACKCPP_NETWORK_USER_HPP

#include "stackcpp/misc/flags.hpp"
#include "stackcpp/misc/types.hpp"
#include "stackcpp/objects/badge_count.hpp"
#include "stackcpp/objects/network_post.hpp"
#include "stackcpp/objects/user.hpp"

#include <rapidjson/document.h>
#include <string>
#include <vector>



namespace stackcpp {

inline namespace objects { struct network_user; }
network_user parse_network_user(const rapidjson::Value&);



inline namespace objects {
struct network_user final {
    unique_id account_id() const noexcept { return account_id_; }
    integer_t answers() const noexcept { return answers_; }
    badge_count badges() const noexcept { return badges_; }
    date_t creation() const noexcept { return creation_; }
    date_t last_accessed() const noexcept { return last_accessed_; }
    integer_t questions() const noexcept { return questions_; }
    integer_t reputation() const noexcept { return reputation_; }
    std::string site() const noexcept { return site_; }
    std::string site_url() const noexcept { return site_url_; }
    std::vector<network_post> top_answers() const noexcept { return top_answers_; }
    std::vector<network_post> top_questions() const noexcept { return top_questions_; }
    unique_id id() const noexcept { return id_; }
    user_type type() const noexcept { return type_; }

private:
    friend network_user stackcpp::parse_network_user(const rapidjson::Value&);

    // See [dcl.fct.def.default]/4 and [dcl.init.aggr]/1 for rational.
    network_user() noexcept {}

    unique_id account_id_;
    integer_t answers_{};
    badge_count badges_;
    date_t creation_;
    date_t last_accessed_;
    integer_t questions_{};
    integer_t reputation_{};
    std::string site_;
    std::string site_url_;
    std::vector<network_post> top_answers_;
    std::vector<network_post> top_questions_;
    unique_id id_;
    user_type type_{};
};
}
}

#endif
