// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.



#ifndef STACKCPP_ORIGINAL_QUESTION_HPP
#define STACKCPP_ORIGINAL_QUESTION_HPP

#include "stackcpp/misc/types.hpp"

#include <rapidjson/document.h>
#include <string>



namespace stackcpp {

inline namespace objects { struct original_question; }
original_question parse_original_question(const rapidjson::Value&);



inline namespace objects {
struct original_question final {
    unique_id accepted_answer_id() const noexcept { return accepted_answer_id_; }
    integer_t answers() const noexcept { return answers_; }
    unique_id id() const noexcept { return id_; }
    std::string title() const noexcept { return title_; }

private:
    friend original_question stackcpp::parse_original_question(const rapidjson::Value&);
    friend struct question;
    friend struct closed_detail;

    // See [dcl.fct.def.default]/4 and [dcl.init.aggr]/1 for rational.
    original_question() noexcept {}

    unique_id accepted_answer_id_;
    integer_t answers_{};
    unique_id id_;
    std::string title_;
};
}
}

#endif
