// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.



#ifndef STACKCPP_QUESTION_TIMELINE_HPP
#define STACKCPP_QUESTION_TIMELINE_HPP

#include "stackcpp/misc/flags.hpp"
#include "stackcpp/misc/types.hpp"
#include "stackcpp/objects/shallow_user.hpp"

#include <rapidjson/document.h>
#include <string>



namespace stackcpp {

inline namespace objects { struct question_timeline; }
question_timeline parse_question_timeline(const rapidjson::Value&);



inline namespace objects {
struct question_timeline final {
    unique_id comment_id() const noexcept { return comment_id_; }
    date_t creation() const noexcept { return creation_; }
    integer_t downvotes() const noexcept { return downvotes_; }
    shallow_user owner() const noexcept { return owner_; }
    unique_id post_id() const noexcept { return post_id_; }
    unique_id question_id() const noexcept { return question_id_; }
    std::string revision_guid() const noexcept { return revision_guid_; }
    question_timeline_type type() const noexcept { return type_; }
    integer_t upvotes() const noexcept { return upvotes_; }
    shallow_user user() const noexcept { return user_; }

private:
    friend question_timeline stackcpp::parse_question_timeline(const rapidjson::Value&);

    // See [dcl.fct.def.default]/4 and [dcl.init.aggr]/1 for rational.
    question_timeline() noexcept {};

    unique_id comment_id_;
    date_t creation_;
    integer_t downvotes_{};
    shallow_user owner_;
    unique_id post_id_;
    unique_id question_id_;
    std::string revision_guid_;
    question_timeline_type type_;
    integer_t upvotes_{};
    shallow_user user_;
};
}
}
#endif
