// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.



#ifndef STACKCPP_QUESTION_HPP
#define STACKCPP_QUESTION_HPP

#include "stackcpp/misc/types.hpp"
#include "stackcpp/objects/answer.hpp"
#include "stackcpp/objects/closed_detail.hpp"
#include "stackcpp/objects/comment.hpp"
#include "stackcpp/objects/migration_info.hpp"
#include "stackcpp/objects/notice.hpp"
#include "stackcpp/objects/shallow_user.hpp"

#include <rapidjson/document.h>
#include <string>
#include <vector>



namespace stackcpp {

inline namespace objects { struct question; }
question parse_question(const rapidjson::Value&);



inline namespace objects {
struct question final {
    unique_id accepted_answer_id() const noexcept { return accepted_answer_id_; }
    std::vector<answer> answers() const noexcept { return answers_; }
    std::string content() const noexcept { return content_; }
    std::string content_markdown() const noexcept { return content_markdown_; }
    integer_t bounty() const noexcept { return bounty_; }
    date_t bounty_end() const noexcept { return bounty_end_; }
    shallow_user bounty_giver() const noexcept { return bounty_giver_; }
    bool close() const noexcept { return close_; }
    bool flag() const noexcept { return flag_; }
    integer_t close_votes() const noexcept { return close_votes_; }
    date_t closed() const noexcept { return closed_; }
    objects::closed_detail closed_detail() const noexcept { return closed_detail_; }
    std::string close_reason() const noexcept { return close_reason_; }
    std::vector<comment> comments() const noexcept { return comments_; }
    date_t community_wiki() const noexcept { return community_wiki_; }
    date_t creation() const noexcept { return creation_; }
    integer_t delete_votes() const noexcept { return delete_votes_; }
    integer_t downvotes() const noexcept { return downvotes_; }
    bool has_downvoted() const noexcept { return has_downvoted_; }
    integer_t favorites() const noexcept { return favorites_; }
    bool has_favorited() const noexcept { return has_favorited_; }
    bool answered() const noexcept { return answered_; }
    date_t last_active() const noexcept { return last_active_; }
    date_t last_edited() const noexcept { return last_edited_; }
    shallow_user last_editor() const noexcept { return last_editor_; }
    std::string url() const noexcept { return url_; }
    date_t locked() const noexcept { return locked_; }
    migration_info migrated_from() const noexcept { return migrated_from_; }
    migration_info migrated_to() const noexcept { return migrated_to_; }
    objects::notice notice() const noexcept { return notice_; }
    shallow_user owner() const noexcept { return owner_; }
    date_t protect() const noexcept { return protect_; }
    unique_id id() const noexcept { return id_; }
    integer_t reopen_votes() const noexcept { return reopen_votes_; }
    integer_t score() const noexcept { return score_; }
    std::string share_url() const noexcept { return share_url_; }
    std::vector<std::string> tags() const noexcept { return tags_; }
    std::string title() const noexcept { return title_; }
    integer_t upvotes() const noexcept { return upvotes_; }
    bool has_upvoted() const noexcept { return has_upvoted_; }
    integer_t views() const noexcept { return views_; }

private:
    friend question stackcpp::parse_question(const rapidjson::Value&);

    // See [dcl.fct.def.default]/4 and [dcl.init.aggr]/1 for rational.
    question() noexcept {}

    unique_id accepted_answer_id_;
    std::vector<answer> answers_;
    std::string content_;
    std::string content_markdown_;
    integer_t bounty_{};
    date_t bounty_end_;
    shallow_user bounty_giver_;
    bool close_{};
    bool flag_{};
    integer_t close_votes_{};
    date_t closed_;
    objects::closed_detail closed_detail_;
    std::string close_reason_;
    std::vector<comment> comments_;
    date_t community_wiki_;
    date_t creation_;
    integer_t delete_votes_{};
    integer_t downvotes_{};
    bool has_downvoted_{};
    integer_t favorites_{};
    bool has_favorited_{};
    bool answered_{};
    date_t last_active_;
    date_t last_edited_;
    shallow_user last_editor_;
    std::string url_;
    date_t locked_;
    migration_info migrated_from_;
    migration_info migrated_to_;
    objects::notice notice_;
    shallow_user owner_;
    date_t protect_;
    unique_id id_;
    integer_t reopen_votes_{};
    integer_t score_{};
    std::string share_url_;
    std::vector<std::string> tags_;
    std::string title_;
    integer_t upvotes_{};
    bool has_upvoted_{};
    integer_t views_{};
};
}
}

#endif
