// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.



#ifndef STACKCPP_REPUTATION_HPP
#define STACKCPP_REPUTATION_HPP

#include "stackcpp/misc/flags.hpp"
#include "stackcpp/misc/types.hpp"
#include "stackcpp/objects/comment.hpp"

#include <string>



namespace stackcpp {

inline namespace objects { struct reputation; }
reputation parse_reputation(const rapidjson::Value&);



inline namespace objects {
struct reputation final {
    std::string url() const noexcept { return url_; }
    date_t time() const noexcept { return time_; }
    unique_id post_id() const noexcept { return post_id_; }
    stackcpp::post_type post_type() const noexcept { return post_type_; }
    integer_t change() const noexcept { return change_; }
    std::string title() const noexcept { return title_; }
    unique_id user_id() const noexcept { return user_id_; }
    stackcpp::vote_type vote_type() const noexcept { return vote_type_; }

private:
    friend reputation stackcpp::parse_reputation(const rapidjson::Value&);

    // See [dcl.fct.def.default]/4 and [dcl.init.aggr]/1 for rational.
    reputation() noexcept {}

    std::string url_;
    date_t time_;
    unique_id post_id_;
    stackcpp::post_type post_type_{};
    integer_t change_{};
    std::string title_;
    unique_id user_id_;
    stackcpp::vote_type vote_type_{};
};
}
}

#endif
