// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.



#ifndef STACKCPP_REVISION_HPP
#define STACKCPP_REVISION_HPP

#include "stackcpp/misc/flags.hpp"
#include "stackcpp/misc/types.hpp"
#include "stackcpp/objects/comment.hpp"
#include "stackcpp/objects/shallow_user.hpp"

#include <rapidjson/document.h>
#include <string>
#include <vector>



namespace stackcpp {

inline namespace objects { struct revision; }
revision parse_revision(const rapidjson::Value&);



inline namespace objects {
struct revision final {
    std::string content() const noexcept { return content_; }
    std::string comment() const noexcept { return comment_; }
    date_t creation() const noexcept { return creation_; }
    bool rollback() const noexcept { return rollback_; }
    std::string last_content() const noexcept { return last_content_; }
    std::vector<std::string> last_tags() const noexcept { return last_tags_; }
    std::string last_title() const noexcept { return last_title_; }
    unique_id post_id() const noexcept { return post_id_; }
    stackcpp::post_type post_type() const noexcept { return post_type_; }
    std::string guid() const noexcept { return guid_; }
    integer_t index() const noexcept { return index_; }
    revision_type type() const noexcept { return type_; }
    bool community_wiki() const noexcept { return community_wiki_; }
    std::vector<std::string> tags() const noexcept { return tags_; }
    std::string title() const noexcept { return title_; }
    shallow_user user() const noexcept { return user_; }

private:
    friend revision stackcpp::parse_revision(const rapidjson::Value&);

    // See [dcl.fct.def.default]/4 and [dcl.init.aggr]/1 for rational.
    revision() noexcept {}

    std::string content_;
    std::string comment_;
    date_t creation_;
    bool rollback_;
    std::string last_content_;
    std::vector<std::string> last_tags_;
    std::string last_title_;
    unique_id post_id_;
    stackcpp::post_type post_type_{};
    std::string guid_;
    integer_t index_{};
    revision_type type_{};
    bool community_wiki_{};
    std::vector<std::string> tags_;
    std::string title_;
    shallow_user user_;
};
}
}

#endif
