// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.



#ifndef STACKCPP_TAG_H
#define STACKCPP_TAG_H

#include "stackcpp/misc/types.hpp"

#include <rapidjson/document.h>
#include <string>
#include <vector>



namespace stackcpp {

inline namespace objects { struct tag; }
tag parse_tag(const rapidjson::Value&);



inline namespace objects {
struct tag final {
    integer_t count() const noexcept { return count_; }
    bool has_synonyms() const noexcept { return has_synonyms_; }
    bool moderator_only() const noexcept { return moderator_only_; }
    bool required() const noexcept { return required_; }
    date_t last_active() const noexcept { return last_active_; }
    std::string name() const noexcept { return name_; }
    std::vector<std::string> synonyms() const noexcept { return synonyms_; }
    unique_id user_id() const noexcept { return user_id_; }

private:
    friend tag stackcpp::parse_tag(const rapidjson::Value&);

    // See [dcl.fct.def.default]/4 and [dcl.init.aggr]/1 for rational.
    tag() noexcept {}

    integer_t count_{};
    bool has_synonyms_{};
    bool moderator_only_{};
    bool required_{};
    date_t last_active_;
    std::string name_;
    std::vector<std::string> synonyms_;
    unique_id user_id_;
};
}
}

#endif
